# Generated by Django 5.2.4 on 2026-06-22 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_user_recovery_pin'),
    ]

    operations = [
        migrations.AddField(
            model_name='amazon',
            name='coefficient_of_variation',
            field=models.FloatField(default=0.0, help_text='Volatility indicator (CV) for this vendor'),
        ),
        migrations.AddField(
            model_name='jumia',
            name='coefficient_of_variation',
            field=models.FloatField(default=0.0, help_text='Volatility indicator (CV) for this vendor'),
        ),
        migrations.AddField(
            model_name='kilimall',
            name='coefficient_of_variation',
            field=models.FloatField(default=0.0, help_text='Volatility indicator (CV) for this vendor'),
        ),
        migrations.AddField(
            model_name='product',
            name='expected_value',
            field=models.FloatField(default=0.0, help_text='Expected mean value across vendors/history'),
        ),
        migrations.AddField(
            model_name='product',
            name='risk_adjusted_score',
            field=models.FloatField(default=0.0, help_text='SmartRank Score: Expected Value - Variance Penalty'),
        ),
        migrations.AddField(
            model_name='product',
            name='var_95',
            field=models.FloatField(default=0.0, help_text='95% Confidence Value-at-Risk'),
        ),
        migrations.AddField(
            model_name='product',
            name='variance_penalty',
            field=models.FloatField(default=0.0, help_text='Penalty applied based on price variance'),
        ),
        migrations.AddField(
            model_name='shopify',
            name='coefficient_of_variation',
            field=models.FloatField(default=0.0, help_text='Volatility indicator (CV) for this vendor'),
        ),
    ]
