# Generated by Django 5.2.4 on 2026-02-04 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='recovery_pin',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
